sylius_shop_password_reset:
    path: /reset-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: sylius_shop_login

sylius_shop_user_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop_user:verifyAction
        _sylius:
            redirect: bitbag_sylius_graphql_shop_user_post_verify
            
bitbag_sylius_graphql_shop_user_post_verify:
    path: /post-verify-action
    methods: [GET]
    controller: bitbag.sylius_graphql_plugin.controller.shop_user_post_verify:postVerifyAction

bitbag_sylius_graphql_shop_product_show:
    path: /p/{id}/{slug}
    methods: [ GET ]
